### ISSUE TITLE
[QMP VI] AccuWeather API faltante

### ISSUE THREAD

**Issue by foviedo** [dds-jv/foro#40]
Hola! Un detalle:
En el enunciado dice que actualizaron AccuWeather para que entienda el mensaje getAlertas, pero esto no está subido
Igual bien podría hacer un método dummy que no devuelva nada, pero lo comento por las dudas

**Comment by roli93** [comment]
No lo subimos adrede. Recuerden que no les pedimos q el código compile. Por ende no deberían tener problemas en usar el método en pseudocódigo sin tener su implementación ;)

Saludos!
