### ISSUE TITLE
Monto establecido de egresos

### ISSUE THREAD

**Issue by julchat** [dds-jv/foro#55]
Hola,
> Bloquear la posibilidad de aceptar nuevos egresos a una determinada entidad, porque la misma superó un monto previamente establecido.

Se refiere a una cantidad máxima de egresos, o un monto de dinero máximo que tiene una entidad para gastar, y con el costo de los demás egresos, esta suma no debería exceder lo establecido?

Gracias

**Comment by SofiCortes** [comment]
Hola @julchat!

Sería un monto de dinero máximo para gastar. De todas formas, si lo interpretaron como cantidad de egresos, también es válido.

**Comment by julchat** [comment]
Gracias!
