### ISSUE TITLE
[Resolución 1er parcial] Rappish

### ISSUE THREAD

**Issue by atta25** [dds-jv/foro#57]
Buenas, adjunto el enunciado y resolución de Rappish, cualquier feedback me vendría muy bien.

![rappish1](https://user-images.githubusercontent.com/14947687/89133844-e1e24580-d4f5-11ea-9fe7-16b13cc3a872.jpeg)
![rappish2](https://user-images.githubusercontent.com/14947687/89133848-e73f9000-d4f5-11ea-9edf-69686cd26fb1.jpeg)
![rappish_diagrama_clases](https://user-images.githubusercontent.com/14947687/89133850-ee669e00-d4f5-11ea-8714-b3a086543375.jpeg)

Acá dejo el .txt con el pseudocódigo y todo lo demás que pide el enunciado: 
[resolucion_rappish.txt](https://github.com/dds-jv/foro/files/5013082/resolucion_rappish.txt)

Saludos.

**Comment by gastonprieto** [comment]
Buenas!

Me llevo un rato, pero te comento lo que vi. 

Asumí que la notación que estas usando es similar a la de case class de scala, para cuando queres definir el constructor y sus atributos obligatorios. Me refiero a esto:

> class PedidoInmediato(List<Item> items) 

---

Yo separaría el item del producto, creo que el producto podría vivir mas que el item, pensalo como un catalogo cuando elegis la comida, tu Producto esta disponible y es el que todos ven, pero tu item es la compra de ese producto para esa venta.

Más allá de eso bien la separación entre Producto y Promo.

---

> item.getPrecioParcial

Lo llamaría precio o precioFinal, porque no hay otro parcial del precio, ese número que te da es final.

---

La clase Entregable no me cierra, tiene una sola responsabilidad que es dar el costo final de un pedido y depende del usuario y el pedido, pero no de nada de ella misma, entonces podrías modelarlo de otras dos formas.

```
usuario.precioPara(pedido)
```

o 

```
pedido.precioCon(usuario)
```

Y el mensaje `entregar()` no estaría encontrando que hace cuando le dice al pedido `realizarEnvio(usuario)`

---

```
class CalculadorDistancia() {
	Double calcular(Posicion posicion, Posicion otraPosicion) {
		// se hace uso de la biblioteca para calcular distancia entre la posición del Usuario y la del Restaurante
		return reglaGigante.distanciaEntre(posicion.x, posicion.y, posicion.z, otraPosicion.x, otraPosicion.y, otraPosicion.z)
	}
}
```

Esto esta mejor que la interfaz anterior, pero estas haciendolo como si fueran funciones, y no aprovechas las ventajas, de los objetos. Ademas si bien no te acoplas a la reglaGigante ahora te acoplas al calculador de distinancias, el que maneje los puntos tiene que saber de puntos y calculador de distancia. 
Fijate que es como que le esta robando una responsabilidad a la posicion.


En cambio podrías haber hecho

```
posicion.distanciaA(posicion)
```

y en este caso la que se acopla a la regla gigante es la posición

---

```Java
		try {
			new EmpaquetadorPedido().preparar(this)
		} catch (NoHayEncargadoException excetion) {
			usuario.notificarNoDisponibilidadEncargados()
		}
```

No hace falta llamar al usuario.notificarNoDisponibilidadEncargados() si la excepción la dejas propagar va a llegar  a la UI y la UI la va a mostrar.

----

continuara....

**Comment by gastonprieto** [comment]
```Java
	void preparar(Pedido pedido) {
		pedido.encargadoSeleccionado = SeleccionadorEncargados.instance.seleccionarPara(pedido)
		RepoPedidos.instance.addPedidoInmediato(pedido)
		new Modulo().informar(pedido)
		pedido.usuario.sumarEstrellas()
	}
```

El modulo parece interactuar con otro sistema, trataría de parametrizarlo de alguna forma y no fijar la instanciación así testearlo es mas fácil.

`RepoPedidos.instance.addPedidoInmediato(pedido)` esto me hace ruido porque en el programado no es un pedido inmediato.

---

Bien la idea del job

--

Personalmente en vez de modelar pedido inmediato y pedido programado, hubiera modelado solo pedido, y para el caso de programado hubiera usado composición, haciendo un PedidoProgramado que tenga un Pedido, y cuando lo asignas lo único que haces es sacarlo del PedidoProgramado y lo manipulas como un pedido normal. Porque pensa que la fecha esa solo se usa cuando se espera para ejecutarse.

**Comment by atta25** [comment]
Buenas, gracias por el feedback, dejo algunas consultas más:
- está bien el pseudocódigo a nivel sintaxis o se prefiere que sea más cercano a Java?

- > Yo separaría el item del producto, creo que el producto podría vivir mas que el item, pensalo como un catalogo cuando elegis la comida, tu Producto esta disponible y es el que todos ven, pero tu item es la compra de ese producto para esa venta.

No entiendo bien eso de que el producto pueda vivir más que el ítem. Te referís a que si separara el Item del Producto, y eliminara el Item, el Producto seguiría teniendo sentido por si mismo? Al margen de eso ahora que lo veo me hace ruido tener una herencia entre Item y Producto, porque un Producto **no es** un Item (herencia).

- > Personalmente en vez de modelar pedido inmediato y pedido programado, hubiera modelado solo pedido, y para el caso de programado hubiera usado composición, haciendo un PedidoProgramado que tenga un Pedido, y cuando lo asignas lo único que haces es sacarlo del PedidoProgramado y lo manipulas como un pedido normal. Porque pensa que la fecha esa solo se usa cuando se espera para ejecutarse.

Esto más que una composición lo entendí como una delegate. El PedidoProgramado conoce un Pedido (normal).

```
#PedidoProgramado(Pedido pedido, LocalDateTime fechaEntrega) {
        // el job terminaría ejecutando este método si es que es la hora de entregar
	void ejecutar() {
		RepoPedidos.instance.addPedidoInmediato(pedido)
		RepoPedidos.instance.removePedidoProgramado(this)		
	}

	Boolean esHoraDeEntregar() {
		return LocalDateTime.now() == fechaEntrega.minusMinutes(45)
	}
}
```

**Comment by gastonprieto** [comment]
> está bien el pseudocódigo a nivel sintaxis o se prefiere que sea más cercano a Java?

Se entendía bastante, así que parece un buen nivel.

> No entiendo bien eso de que el producto pueda vivir más que el ítem. Te referís a que si separara el Item del Producto, y eliminara el Item, el Producto seguiría teniendo sentido por si mismo? Al margen de eso ahora que lo veo me hace ruido tener una herencia entre Item y Producto, porque un Producto no es un Item (herencia).

Claro, pensa que seguro alguien tuvo que cargar los productos en el sistema, ponerle el precio, armar combos, etc. Y todo eso se hace antes de que el usuario decida la cantidad por ejemplo, entonces la información de producto debería existir antes del item y no estar acoplado al ciclo de vida del item. Y como bien vos decís un Producto no es un item.

> Esto más que una composición lo entendí como una delegate. El PedidoProgramado conoce un Pedido (normal).

No estoy muy seguro en la diferencia que queres decir, pero la solución es la misma que pense.

**Comment by atta25** [comment]
> Personalmente en vez de modelar pedido inmediato y pedido programado, hubiera modelado solo pedido, y para el caso de programado hubiera usado composición, haciendo un PedidoProgramado que tenga un Pedido, y cuando lo asignas lo único que haces es sacarlo del PedidoProgramado y lo manipulas como un pedido normal. Porque pensa que la fecha esa solo se usa cuando se espera para ejecutarse.

Cuando me hablaste de composición enseguida pensé en que un objeto A conoce a un objeto B, y este último es una superclase o una interfaz. Entonces para que exista una Composición no es necesario que exista una jerarquía de clases?

**Comment by gastonprieto** [comment]
Estrictamente no, hay como varias formas de llamar a la relación entre A y B, asociación es el nombre generico y agregación/composición son casos especificos, la diferencia es conceptual, agregación es cuando B tiene una vida independiente de A y composición es cuando B debería solo existir si esta en un A.

Lo que pasa es que casi siempre hablamos de composición cuando estamos comparando con herencia, entonces seguro por eso pensaste en eso.

**Comment by atta25** [comment]
Clarísimo @gastonprieto gracias!! Por mi parte no me quedan más dudas con este parcial.

Saludos.
