### ISSUE TITLE
Cómo instalar MySQL?

### ISSUE THREAD

**Issue by foviedo** [dds-jv/foro#68]
Buenas! Cómo va? Una consulta. Qué es lo que hay que instalar de MySQL para tenerlo funcional para poder usarlo con Java? 
Desde este link
https://dev.mysql.com/downloads/windows/installer/8.0.html
Te descarga un instalador de esos que te dejan elegir qué de todo instalar, pero hay boche de cosas y hay uno que dice "lo mínimo y necesario" que parece no haberme instalado nada y hay un full que instala mil cosas
![image](https://user-images.githubusercontent.com/48896107/92427839-f1dbed80-f163-11ea-824d-81d2bacecfb6.png)
Y bueno, cada cosa también tiene su versión propia, así que si hay alguna sugerencia es bienvenida
Gracias de antemano!

**Comment by gastonprieto** [comment]
Buenas @foviedo !

Tenes que instalar el servidor (mysql server) con eso debería alcanzarte, por otro lado si queres podes bajarte el workbench que es el que suelo usar en la clase para ejecutar las consultas. 

Sino también podes usar dbeaver (https://dbeaver.io/) que es un client sql pero para distintos motores, no solo para mysql.

**Comment by foviedo** [comment]
Joya Gastón, te agradezco mil

**Comment by foviedo** [comment]
Buenas @gastonprieto lo vuelvo a abrir: tratando de seguir el tutorial, no puedo correr los test básicamente porque no tengo la base de datos jugadores o prueba, Hay un backup de esta para que la podamos levantar y ver si tengo todo bien?

**Comment by brianstremel** [comment]
Fijate de tirar un 
CREATE DATABASE database_name;
CREATE USER 'unNombreDeUsuario'@'localhost' IDENTIFIED BY 'password';  --Va todo entre las comillas simples, no se las saqués
GRANT ALL PRIVILEGES ON database_name.* TO 'unNombreDeUsuario'@'localhost';

**Comment by gastonprieto** [comment]
@foviedo eso que dice @brianstremel o también desde la UI de mysql client te deja crearla con un boton, dice create database o create schema tal vez.

**Comment by foviedo** [comment]
Me funcionó! Gracias
